name: Check

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  schedule:
    # Nightly tests run on master by default:
    #   Scheduled workflows run on the latest commit on the default or base branch.
    #   (from https://help.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule)
    - cron: "6 0 * * *"


jobs:
  at20:
    runs-on: ubuntu-latest
    name: AmberTools
    env:
      CURRENT_AT_VERSION: "20.0"
      CURRENT_AT_PATCH: "15"

    steps:
      - name: Check latest patch
        id: check
        run: |
          set -x
          next_patch=$(( $CURRENT_AT_PATCH + 1 ))
          http_status=$(curl -s -o /dev/null -I -w "%{http_code}" "https://ambermd.org/bugfixes/AmberTools/$CURRENT_AT_VERSION/update.$next_patch")
          if [[ $http_status == 200 ]]; then
            echo "New patch $next_patch available for AmberTools $CURRENT_AT_VERSION!"
            echo "::set-output name=next_patch::$next_patch"
          fi

      - uses: actions/checkout@v2
      - uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NEW_AT_PATCH: ${{ steps.check.outputs.next_patch }}
        if: steps.check.outputs.next_patch